Updated comments and check case where a Mathematica installation directory exists but it does not contain the MathLink libraries

diff --git a/trunk/ptclassic/bin/mathRootDir b/trunk/ptclassic/bin/mathRootDir
--- a/trunk/ptclassic/bin/mathRootDir
+++ b/trunk/ptclassic/bin/mathRootDir
@@ -1,9 +1,11 @@
 #!/bin/csh -f
 #
 # Script to find the root (installation) Mathematica directory.  Used by
-# makefiles to determine the location of the external interface library.
-# It returns either the path name of the root Mathematica directory or an
-# empty string.
+# makefiles to determine the location of the MathLink external interface
+# library.  If the script finds a root Mathematica directory that contains
+# the sub-directories Bin/MathLink and Source/Includes, then the script
+# will return the root Mathematica directory.  Otherwise, it returns
+# an empty string.
 #
 # Author:  Brian L. Evans
 # Version: $Id$
@@ -47,12 +49,9 @@ if ( ! $?mmapath ) then
 endif
 #
 #  If the math script is found, then
-#  1. the first while statement will determine the full path name of the
-#     math script by following a finite number of symbolic links.
-#  2. the second while statement will back up one directory at a time
-#     along the full math script path name to find the Mathematica root
-#     directory which contains the external interface sub-directories
-#     extern/include and extern/lib
+#  1. extract the mathdir setting from the "math" script
+#  2. make sure that the mathdir setting is valid:  the mathdir should
+#     have Source/Includes and Bin/MathLink sub-directories
 #
 if ( ! $?mmapath ) then
   echo ""
@@ -68,11 +67,21 @@ else
     set newdir = "$mmapath:h"
     set newpath = "$newdir/$newpath"
   endif
-  set mathlinklibdir = $newpath/Bin/MathLink
-  set mathlinkincdir = $newpath/Source/Includes
-  if ( -x $mathlinklibdir && -r $mathlinklibdir && -d $mathlinklibdir && \
+  set mathlinksource = $newpath/Source
+  set mathlinkincdir = $mathlinksource/Includes
+  if ( -x $mathlinksource && -r $mathlinksource && -d $mathlinksource && \
        -x $mathlinkincdir && -r $mathlinkincdir && -d $mathlinkincdir ) then
-    echo $newpath
+    set mathlinkbin = $newpath/Bin
+    set mathlinklib = $mathlinkbin/MathLink
+    if ( -x $mathlinkbin && -r $mathlinkbin && -d $mathlinkbin && \
+         -x $mathlinklib && -r $mathlinklib && -d $mathlinklib ) then
+        echo $newpath
+    else
+	echo ""
+	# Installation error: no Bin/MathLink sub-directory
+	# echo "Found the Mathematica installation directory '$newpath', but it did not contain a Bin/MathLink sub-directory." >! /dev/tty
+	# exit 1
+    endif
   else
     echo ""
   endif
