Added -java option

diff --git a/ptclassic/tycho/bin/tycho b/ptclassic/tycho/bin/tycho
--- a/ptclassic/tycho/bin/tycho
+++ b/ptclassic/tycho/bin/tycho
@@ -18,7 +18,7 @@
 
 set usagestring = "Usage: $0 [-debug] [-ptiny|-ptrim|-pigi|-bin tychobin] [-nowelcome] [-noconsole] [-e tclscript] [-bak] [file...]"
 
-set argError = "Usage: $0 -ptiny, -ptrim, -pigi and -bin xxx are mutually exclusive"
+set argError = "Usage: $0 -ptiny, -ptrim, -pigi, -bin xxx and -java are mutually exclusive"
 
 if ( ! $?DISPLAY ) then
 	echo "${0}: Your DISPLAY environment variable must be set"
@@ -36,7 +36,8 @@ while ($#argv)
 			echo " -ptrim         Small version, more domains"
 			echo " -pigi          Big version, many domains"
 			echo " -bin tychobin  Run the binary 'tychobin'"
-			echo " -bak           Run a .bak binary"
+			echo " -java          Run with the Tcl/Java interface"
+  			echo " -bak           Run a .bak binary"
 			echo " -nowelcome     No welcome window"
 			echo " -noconsole     No console window"
 			echo " -e tclfile     Start up and source tclfile"
@@ -47,7 +48,7 @@ while ($#argv)
 			set tychodebug
 			breaksw
 		case -ptiny:
-			if ( $?selectPtolemy ) then
+			if ( $?selectPtolemy || $?selectJava) then
 				echo $argError
 				exit 2
 			endif
@@ -55,7 +56,7 @@ while ($#argv)
 			set tychoptiny
 			breaksw
 		case -ptrim:
-			if ( $?selectPtolemy ) then
+			if ( $?selectPtolemy || $?selectJava) then
 				echo $argError
 				exit 2
 			endif
@@ -63,7 +64,7 @@ while ($#argv)
 			set tychoptrim
 			breaksw
 		case -pigi:
-			if ( $?selectPtolemy ) then
+			if ( $?selectPtolemy || $?selectJava) then
 				echo $argError
 				exit 2
 			endif
@@ -71,13 +72,21 @@ while ($#argv)
 			set tychopigi
 			breaksw
 		case -bin:
-			if ( $?selectPtolemy ) then
+			if ( $?selectPtolemy || $?selectJava) then
 				echo $argError
 				exit 2
 			endif
 			set selectPtolemy
 			set prog = $argv[2]
 			shift
+			breaksw
+		case -java:
+			if ( $?selectPtolemy || $?selectJava) then
+				echo $argError
+				exit 2
+			endif
+			set selectJava
+			set tychojava
 			breaksw
 		case -bak:
 			set tychobak
@@ -127,7 +136,12 @@ if ( ! -d "$TYCHO") then
 	exit 2
 endif
 
-if ( ! $?selectPtolemy) then
+# We could use an if/else/if/else here, but the indentation makes
+# it hard to read
+
+##################################################################
+# itkwish
+if (! $?selectPtolemy && ! $?selectJava) then
 	# We did not select Ptolemy, so we just assume that itkwish
 	# is in the users path.  Bad idea?  One alternative would be
 	# to see if $PTOLEMY is set and then check for 
@@ -147,9 +161,12 @@ if ( ! $?selectPtolemy) then
 	else
 		set prog = (itkwish -f \"\$TYCHO/kernel/Tycho.tcl\")
 	endif
-else
-	# We selected Ptolemy
+endif 
 
+##################################################################
+# Ptolemy, no Java
+if ( $?selectPtolemy && ! $?selectJava) then
+	# We selected Ptolemy
 	if ( ! $?PTOLEMY ) setenv PTOLEMY ~ptolemy
 
 	if ( ! -r "$PTOLEMY/bin/ptsetup.csh" ) then
@@ -217,7 +234,37 @@ else
 		    set prog = $prog.bak
 		endif
 	endif
-endif # !?selectPtolemy
+endif # ?selectPtolemy
+
+##################################################################
+# Java
+if ( ! $?selectPtolemy && $?selectJava) then
+	# We selected java
+
+	# Add $Tycho/lib.$PTARCH to LD_LIBRARY_PATH so we can find libjtk.so
+	# Note that under hpux, this file will be libjtk.sl, so we can't
+	# easily check
+	setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${TYCHO}/lib.${PTARCH}
+	if ( ! $?CLASSPATH ) then
+		if ( -f ~/java/lib/classes.zip) then
+			setenv CLASSPATH ~/java/lib/classes.zip
+			echo "${0}: CLASSPATH is not set,"
+			echo "  setting it to $CLASSPATH"
+		else if ( -f /opt/SUNWjws/JDK/lib/classes.zip) then
+			setenv CLASSPATH /opt/SUNWjws/JDK/lib/classes.zip
+			echo "${0}: CLASSPATH is not set,"
+			echo "  setting it to $CLASSPATH"
+		else
+			echo" ${0}: Could not find classes.zip, you must set CLASSPATH"	
+			exit 4
+		endif
+	endif
+
+	set prog = (java -classpath ${CLASSPATH}:${TYCHO}/lib/java:${TYCHO}/lib/java/tycho Tycho)
+
+endif
+
+##################################################################
 
 if ( "$1" =~ "-*" ) then
     echo "${0}: Bad option: $1"
