Minor tweaks for jdk1.1

diff --git a/ptclassic/tycho/bin/tycho b/ptclassic/tycho/bin/tycho
--- a/ptclassic/tycho/bin/tycho
+++ b/ptclassic/tycho/bin/tycho
@@ -284,14 +284,36 @@ if ( ! $?selectPtolemy && $?selectJava) then
 	endif
 
 
+	if ( ! $?CLASSPATH ) then
+		if ( -f ~/java/lib/classes.zip) then
+			setenv CLASSPATH ~/java/lib/classes.zip
+			if ( ! $?JAVA_HOME ) then
+				setenv JAVA_HOME ~/java
+			endif
+			echo "${0}: CLASSPATH is not set,"
+			echo "  setting it to $CLASSPATH"
+		else if ( -f /opt/jdk1.1/lib/classes.zip) then
+			setenv CLASSPATH /opt/jdk1.1/lib/classes.zip
+			if ( ! $?JAVA_HOME ) then
+				setenv JAVA_HOME /opt/jdk1.1
+			endif
+			echo "${0}: CLASSPATH is not set,"
+			echo "  setting it to $CLASSPATH"
+		else
+			echo" ${0}: Could not find classes.zip, you must set CLASSPATH"	
+			exit 4
+		endif
+	endif
+
+
 	# Add $Tycho/lib.$PTARCH to LD_LIBRARY_PATH so we can find libjtk.so
 	# Note that under hpux, this file will be libjtk.sl, so we can't
 	# easily check
 	if ($PTARCH =~ sol?*) then	
 		if ( ! $?LD_LIBRARY_PATH ) then
-	   	   setenv LD_LIBRARY_PATH ${TYCHO}/lib.${PTARCH}:${PTOLEMY}/tcltk/itcl.${PTARCH}/lib/itcl
+	   	   setenv LD_LIBRARY_PATH ${TYCHO}/lib.${PTARCH}:${PTOLEMY}/tcltk/itcl.${PTARCH}/lib/itcl:
 		else
-	   	   setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${TYCHO}/lib.${PTARCH}:${PTOLEMY}/tcltk/itcl.${PTARCH}/lib/itcl
+	   	   setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${TYCHO}/lib.${PTARCH}:${PTOLEMY}/tcltk/itcl.${PTARCH}/lib/itcl:
 		endif
 	endif
 
@@ -300,25 +322,6 @@ if ( ! $?selectPtolemy && $?selectJava) then
 	   	   setenv SHLIB_PATH ${TYCHO}/lib.${PTARCH}:${PTOLEMY}/tcltk/itcl.${PTARCH}/lib/itcl
 		else
 	   	   setenv SHLIB_PATH ${SHLIB_PATH}:${TYCHO}/lib.${PTARCH}:${PTOLEMY}/tcltk/itcl.${PTARCH}/lib/itcl
-		endif
-	endif
-
-	if ( ! $?CLASSPATH ) then
-		if ( -f ~/java/lib/classes.zip) then
-			setenv CLASSPATH ~/java/lib/classes.zip
-			echo "${0}: CLASSPATH is not set,"
-			echo "  setting it to $CLASSPATH"
-		else if ( -f /opt/jdk1.1/lib/classes.zip) then
-			setenv CLASSPATH /opt/jdk1.1/lib/classes.zip
-			echo "${0}: CLASSPATH is not set,"
-			echo "  setting it to $CLASSPATH"
-		else if ( -f /opt/SUNWjws/JDK/lib/classes.zip) then
-			setenv CLASSPATH /opt/SUNWjws/JDK/lib/classes.zip
-			echo "${0}: CLASSPATH is not set,"
-			echo "  setting it to $CLASSPATH"
-		else
-			echo" ${0}: Could not find classes.zip, you must set CLASSPATH"	
-			exit 4
 		endif
 	endif
 
